FROM logicalparadox/ubuntu:14.04
MAINTAINER Jake Luer "jake@alogicalparadox.com"

RUN apt-get -q update
RUN apt-get -qy upgrade 
RUN apt-get -qy install python python-dev python-pip python-virtualenv
